from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional

from apps.retrieval.rag_join_orchestration import (
    JoinOrchestrationRuntime,
    PerfFollowupRuntime,
    resolve_perf_followup_join_ids as run_perf_followup_join_ids,
)


def resolve_perf_followup_join_ids_for_request(
    *,
    request: Any,
    preset: Any,
    qdr: Any,
    log_kv: Callable[..., None],
    get_relation_route: Callable[[Any], Any],
    build_tag_only_filter: Callable[[List[str]], Any],
    and_filter: Callable[[Any, Any], Any],
    named_vectors_in_collection: Callable[[Any, str], Any],
    get_pre_vecs: Callable[[str], Dict[str, Any]],
    call_dense_retrieve_hybrid_multi: Callable[..., Dict[str, Any]],
    apply_dense_threshold: Callable[..., None],
    ensure_collection_mark: Callable[[List[Any], str], None],
    rank_source_factory: Callable[..., Any],
    use_dense_score_weight: Callable[[], bool],
    dense_score_weight: Callable[[List[Any]], float],
    rrf_merge: Callable[..., List[Any]],
    dedup_by_doc_id: Callable[[List[Any]], List[Any]],
    final_rerank: Callable[..., List[Any]],
    hydrate_points: Callable[..., None],
    count_missing_join_keys: Callable[..., Dict[str, int]],
    debug_force_join_keys_enabled: Callable[[], bool],
    get_meta: Callable[[dict], dict],
    pick_first: Callable[..., str],
    extract_join_keys: Callable[..., Any],
) -> List[str]:
    """Resolve follow-up perf join ids from concrete collaborators instead of a dispatch runtime basket."""

    return run_perf_followup_join_ids(
        request=request,
        runtime=PerfFollowupRuntime(
            qdr=qdr,
            preset=preset,
            log_kv=log_kv,
            get_relation_route_fn=get_relation_route,
            build_tag_only_filter_fn=build_tag_only_filter,
            and_filter_fn=and_filter,
            named_vectors_in_collection_fn=named_vectors_in_collection,
            get_pre_vecs_fn=get_pre_vecs,
            call_dense_retrieve_hybrid_multi_fn=call_dense_retrieve_hybrid_multi,
            apply_dense_threshold_fn=apply_dense_threshold,
            ensure_collection_mark_fn=ensure_collection_mark,
            rank_source_factory=rank_source_factory,
            use_dense_score_weight_fn=use_dense_score_weight,
            dense_score_weight_fn=dense_score_weight,
            rrf_merge_fn=rrf_merge,
            dedup_by_doc_id_fn=dedup_by_doc_id,
            final_rerank_fn=final_rerank,
            hydrate_points_fn=hydrate_points,
            count_missing_join_keys_fn=count_missing_join_keys,
            debug_force_join_keys_enabled_fn=debug_force_join_keys_enabled,
            get_meta_fn=get_meta,
            pick_first_fn=pick_first,
            extract_join_keys_fn=extract_join_keys,
        ),
    )


def build_join_runtime(
    *,
    qdr: Any,
    preset: Any,
    log_kv: Callable[..., None],
    log_top_points: Callable[..., None],
    log_section: Callable[..., None],
    timing_put: Callable[[Dict[str, Any], str, Any], None],
    point_summary: Callable[[Any], Any],
    named_vectors_in_collection: Callable[[Any, str], Any],
    get_pre_vecs: Callable[[str], Dict[str, Any]],
    call_dense_retrieve_hybrid_multi: Callable[..., Dict[str, Any]],
    validate_lookup_join_hybrid_metrics: Callable[..., None],
    apply_dense_threshold: Callable[..., None],
    ensure_collection_mark: Callable[[List[Any], str], None],
    rank_source_factory: Callable[..., Any],
    use_dense_score_weight: Callable[[], bool],
    dense_score_weight: Callable[[List[Any]], float],
    rrf_merge: Callable[..., List[Any]],
    dedup_by_doc_id: Callable[[List[Any]], List[Any]],
    final_rerank: Callable[..., List[Any]],
    hydrate_points: Callable[..., None],
    count_missing_join_keys: Callable[..., Dict[str, int]],
    debug_force_join_keys_enabled: Callable[[], bool],
    get_meta: Callable[[dict], dict],
    pick_first: Callable[..., str],
    build_people_filter: Callable[..., Any],
    people_filter_input_factory: Callable[..., Any],
    build_project_id_filter: Callable[[List[str], List[str]], Any],
    build_collection_join_filter: Callable[..., Any],
    join_filter_input_factory: Callable[..., Any],
    build_tag_only_filter: Callable[[List[str]], Any],
    and_filter: Callable[[Any, Any], Any],
    with_org_must_gate: Callable[..., Any],
    serialize_filter_for_log: Callable[[Any], Any],
    diff_filter_spec: Callable[..., Dict[str, Any]],
    merge_log_fields: Callable[[dict, dict], dict],
    extract_join_keys: Callable[..., Any],
    resolve_group_pjt_ids: Callable[..., List[str]],
    validate_resolved_join_keys: Callable[..., None],
    get_relation_route: Callable[[Any], Any],
    context_builder: Callable[..., Any],
    payload_get: Optional[Callable[..., Any]] = None,
    series_builder: Optional[Callable[..., Optional[Dict[str, Any]]]] = None,
    multi_hop_bundle_builder: Optional[Callable[..., Optional[Dict[str, Any]]]] = None,
) -> JoinOrchestrationRuntime:
    """Build join orchestration runtime directly from concrete collaborators."""

    return JoinOrchestrationRuntime(
        qdr=qdr,
        preset=preset,
        log_kv=log_kv,
        log_top_points=log_top_points,
        log_section=log_section,
        timing_put_fn=timing_put,
        point_summary_fn=point_summary,
        named_vectors_in_collection_fn=named_vectors_in_collection,
        get_pre_vecs_fn=get_pre_vecs,
        call_dense_retrieve_hybrid_multi_fn=call_dense_retrieve_hybrid_multi,
        validate_lookup_join_hybrid_metrics_fn=validate_lookup_join_hybrid_metrics,
        apply_dense_threshold_fn=apply_dense_threshold,
        ensure_collection_mark_fn=ensure_collection_mark,
        rank_source_factory=rank_source_factory,
        use_dense_score_weight_fn=use_dense_score_weight,
        dense_score_weight_fn=dense_score_weight,
        rrf_merge_fn=rrf_merge,
        dedup_by_doc_id_fn=dedup_by_doc_id,
        final_rerank_fn=final_rerank,
        hydrate_points_fn=hydrate_points,
        count_missing_join_keys_fn=count_missing_join_keys,
        debug_force_join_keys_enabled_fn=debug_force_join_keys_enabled,
        get_meta_fn=get_meta,
        pick_first_fn=pick_first,
        build_people_filter_fn=build_people_filter,
        people_filter_input_factory=people_filter_input_factory,
        build_project_id_filter_fn=build_project_id_filter,
        build_collection_join_filter_fn=build_collection_join_filter,
        join_filter_input_factory=join_filter_input_factory,
        build_tag_only_filter_fn=build_tag_only_filter,
        and_filter_fn=and_filter,
        with_org_must_gate_fn=with_org_must_gate,
        serialize_filter_for_log_fn=serialize_filter_for_log,
        diff_filter_spec_fn=diff_filter_spec,
        merge_log_fields_fn=merge_log_fields,
        extract_join_keys_fn=extract_join_keys,
        resolve_group_pjt_ids_fn=resolve_group_pjt_ids,
        validate_resolved_join_keys_fn=validate_resolved_join_keys,
        get_relation_route_fn=get_relation_route,
        context_builder=context_builder,
        payload_get_fn=payload_get,
        series_builder_fn=series_builder,
        multi_hop_bundle_builder_fn=multi_hop_bundle_builder,
    )
